pipeline {
    agent any

    stages {
              
        stage('Paso 1: Iniciando pipeline Modelo Machine Learning') {
            steps {
                script {
                    echo "Modulo 16 SOE"
                    echo "Ejecutando en: ${env.WORKSPACE}"
                }
            }
        }
        
        stage('Paso 2: Instalando pre-requisitos') {
            steps {
                script {
                    dir("${env.WORKSPACE}/section-05-production-model-package/requirements") {
                        sh "/usr/bin/pip install -r ./requirements.txt"
                        sh "/usr/bin/pip install -r ./test_requirements.txt"
                    }
                }
            }
        }
        
        stage('Paso 3: Ejecución pruebas unitarias') {
            steps {
                script {
                    dir("${env.WORKSPACE}/section-05-production-model-package") {
                        sh "/usr/bin/tox -c ${env.WORKSPACE}/section-05-production-model-package/tox.ini"
                    }
                }
            }
        }

        stage('Paso 4: Comprimiendo proyecto') {
            steps {
                script {
                    dir("${env.WORKSPACE}") {
                        sh "rm -fr modelo.tgz"
                        sh "rm -fr to_deploy"
                        sh "mkdir to_deploy"
                        sh "cp -pr  section-05-production-model-package to_deploy"
                        sh "cp -pr  section-08-deploying-with-containers to_deploy"
                        sh "rm -fr  to_deploy/section-05-production-model-package/.tox"
                        sh "tar cvzf to_deploy/modelo.tgz to_deploy/*"
                    }
                }
            }
        }
        
        stage('Paso 5: Eliminando versión previa en AMAZON') {
            steps {
               sh "ssh -i '/var/jenkins_home/llaves_aws.pem' ubuntu@ec2-44-202-220-76.compute-1.amazonaws.com 'sh /home/ubuntu/bajar.sh'"
            }    
        }
        
        stage('Paso 6: Copiando proyecto en AMAZON') {
            steps {
                script {
                    dir("${env.WORKSPACE}") {
                        sh "scp -i /var/jenkins_home/llaves_aws.pem to_deploy/modelo.tgz ubuntu@ec2-44-202-220-76.compute-1.amazonaws.com:/home/ubuntu/modelo"
                    }
                }
            }
        }
        
        stage('Paso 7: Despliegue de proyecto en AMAZON') {
            steps {
               sh "ssh -i '/var/jenkins_home/llaves_aws.pem' ubuntu@ec2-44-202-220-76.compute-1.amazonaws.com 'sh /home/ubuntu/instalar.sh &'"
            }
        }
        
        stage('Paso 8: Verificación interfaz ML en AMAZON') {
            steps {
               sh "sleep 5s"
               sh "curl \"http://ec2-44-202-220-76.compute-1.amazonaws.com:8010/api/v1/health\" "
            }
        }             
        
    }
}
