pipeline{
    agent any
    
    stages{
        stage('Checkout...'){
            steps{
                echo "Checkout code..."
            }
        }
        
        stage('Hello'){
            steps{                
                sh "python section-08-deploying-with-containers/hello.py"                
            }
        }
        
        stage('TOX-Train model..'){
            steps{
                echo "Deploying to test env..."
                //sh "python section-05-production-model-package/regression_model/train_pipeline.py"
                sh 'cd section-05-production-model-package/'
                sh "python3 tox -e test_package"
            }
        }

        stage('Deploying to prod'){
            steps{
                echo "Deploying to prod env..."
            }
        }
    }
}